bugfix for python 3.8.x
```
TypeError: Optional[t] requires a single type. Got Field(name=None,type=None,default='absolute',default_factory=<dataclasses._MISSING_TYPE object at 0x.
```

Cause by global namespace confusion with class attributes named 'type' and using a type hint like t.Optional[type].

Resolution: Replaced with t.Any.